version: '3.8'

services:
  app:
    build: ./backend
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - praca-network
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/backup:/backup
    networks:
      - praca-network
    restart: unless-stopped
    ports:
      - "${DB_PORT:-5432}:5432"

volumes:
  postgres_data:

networks:
  praca-network:
    driver: bridge